id: IFB94B8AD
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:25:53.548135
last_modified: 2023-02-10 00:25:53.548238
source_metadata:
  title: 'Asaṅga: Triśatikāyāḥ Prajñāpāramitāyāḥ Kārikāsaptatiḥ'
  language: zh
bases:
  2E99:
    base_file: 2E99.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
